Pipelines exportacao
SamuelPerroni/Tech-Challenge-1 pull request #18
Opened 2024-05-17 03:12 UTC by AmericoAlves35

Refatoração pipeline_exportação para atender aos padroes;
O formato final seria o seguinte:

Pais (Coluna ja feita por padrão)
Ano (transformada via pd.melt)
Tipo (São 4 planilhas, logo 4 tipos: Vinhos de mesa, Espumantes, Ucas frescas, Suco de uva - essa implementação é bem semelhante a realizada no pipeline de processamento.)
Quantidade
Valor

2024-05-22 22:56 UTC, fsilvalucas requested changes
Algumas coisas a serem removidas do código.

2024-05-22 22:56 UTC, fsilvalucas commented on api/exportacao/models.py
>      __tablename__ = "exportacao"
Isso aqui pode ser removido

2024-05-22 22:56 UTC, fsilvalucas commented on data/Exportacao/nodes.py
> +# Função de teste detalhada
Isso pode ser removido

2024-05-22 22:56 UTC, fsilvalucas commented on data/Exportacao/pipeline.py
> +"""def run_tests():
Pode ser removido

2024-05-22 22:56 UTC, fsilvalucas commented on api/exportacao/models.py
>      __tablename__ = "exportacao"
Você ja define o __tablename__ logo no inicio da classe. Não é necessário duas definições

2024-05-22 22:58 UTC, fsilvalucas commented on data/Exportacao/pipeline.py
> +"""def run_tests():
Você pode mover os tests para dentro de tests/ mas focando em tests unitários (pequenas funções testando partes singulares do código).

2024-05-25 17:32 UTC, AmericoAlves35 commented
refatoração e testes para API exportaçao

2024-05-26 17:57 UTC, fsilvalucas approved these changes

2024-05-26 17:57 UTC, merged